export const LOAD_LOCATIONS_SUCCESS = 'LOAD_LOCATIONS_SUCCESS';
export const LOAD_TYPES_SUCCESS = 'LOAD_TYPES_SUCCESS';
export const LOAD_BATHS_SUCCESS = 'LOAD_BATHS_SUCCESS';
export const LOAD_SETTINGS_SUCCESS = 'LOAD_SETTINGS_SUCCESS';
export const SET_SETTING_SUCCESS = 'SET_SETTING_SUCCESS';